### ISSUE TITLE
WAB LocalLayer error

### ISSUE THREAD

**Issue by daveyadams** [cmndrbensisko/LocalLayer#46]
I've added the widget to the WAB 1.2 widgets folder so it shows in the widgets pool for selection in a new application. It all works in terms of configuring so I can drop the default listed layers and add in my own dynamic service from our own AGS. However when I launch the app and click the button I get an error, which as a novice I find difficult to solve. I'm not sure if it's something I have failed to configure. Any help would be greatly appreciated - the widget seems perfect for our requirements.

TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at TypeError (native)
    at Object.b.place (http://js.arcgis.com/3.14/init.js:148:448)
    at declare.setPosition (http://ws211:3344/webappbuilder/apps/6/jimu.js/BaseWidget.js:235:12)
    at null.<anonymous> (http://ws211:3344/webappbuilder/apps/6/jimu.js/OnScreenWidgetIcon.js:120:18)
    at http://js.arcgis.com/3.14/init.js:167:296
    at k (http://js.arcgis.com/3.14/init.js:189:431)
    at m (http://js.arcgis.com/3.14/init.js:189:357)
    at resolve (http://js.arcgis.com/3.14/init.js:191:441)
    at null.<anonymous> (http://ws211:3344/webappbuilder/apps/6/jimu.js/WidgetManager.js:117:25)
    at http://js.arcgis.com/3.14/init.js:167:296 "TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at TypeError (native)
    at Object.b.place (http://js.arcgis.com/3.14/init.js:148:448)
    at declare.setPosition (http://ws211:3344/webappbuilder/apps/6/jimu.js/BaseWidget.js:235:12)
    at null.<anonymous> (http://ws211:3344/webappbuilder/apps/6/jimu.js/OnScreenWidgetIcon.js:120:18)
    at http://js.arcgis.com/3.14/init.js:167:296
    at k (http://js.arcgis.com/3.14/init.js:189:431)
    at m (http://js.arcgis.com/3.14/init.js:189:357)
    at resolve (http://js.arcgis.com/3.14/init.js:191:441)
    at null.<anonymous> (http://ws211:3344/webappbuilder/apps/6/jimu.js/WidgetManager.js:117:25)
    at http://js.arcgis.com/3.14/init.js:167:296
    ----------------------------------------
    rejected at a (http://js.arcgis.com/3.14/init.js:190:337)
    at k (http://js.arcgis.com/3.14/init.js:190:89)
    at m (http://js.arcgis.com/3.14/init.js:189:357)
    at resolve (http://js.arcgis.com/3.14/init.js:191:441)
    at null.<anonymous> (http://ws211:3344/webappbuilder/apps/6/jimu.js/WidgetManager.js:117:25)
    at http://js.arcgis.com/3.14/init.js:167:296
    ----------------------------------------
Error
    at then.b.then (http://js.arcgis.com/3.14/init.js:192:253)
    at declare.switchToOpen (http://ws211:3344/webappbuilder/apps/6/jimu.js/OnScreenWidgetIcon.js:118:10)
    at declare.onClick (http://ws211:3344/webappbuilder/apps/6/jimu.js/OnScreenWidgetIcon.js:61:14)
    at null.<anonymous> (http://ws211:3344/webappbuilder/apps/6/jimu.js/OnScreenWidgetIcon.js:37:14)
    at HTMLDivElement.<anonymous> (http://js.arcgis.com/3.14/init.js:167:296)"

**Comment by cmndrbensisko** [comment]
Did you end up resolving this?

**Comment by daveyadams** [comment]
Yes - I asked also on GeoNet and Robert S pointed out I had missed a configuration step. Many thanks for replying.
