### ISSUE TITLE
Local Layer Widget window not closing or responding

### ISSUE THREAD

**Issue by sindile** [cmndrbensisko/LocalLayer#59]
I am using Web AppBuilder v2.2

I have enabled LocalLayer Widget, but the window is not responding.

LocateButton::navigator.geolocation requires a secure origin.
Load widgetOnScreen: 358ms
Object {layers: Object, review: false}
Uncaught TypeError: Cannot read property '_tables' of undefined
    at Object.<anonymous> (http://mylaptop:3344/webappbuilder/apps/3/widgets/LocalLayer/setting/Setting.js?wab_dv=2.2:89:78)
    at Object.c [as destroy] (http://js.arcgis.com/3.18/init.js:118:438)
    at Object.onClose (http://mylaptop:3344/webappbuilder/builder/main.js?wab_dv=2.2:3709:384)
    at Object.onOk (http://mylaptop:3344/webappbuilder/builder/main.js?wab_dv=2.2:3708:370)
    at Object.onClick (http://js.arcgis.com/3.18/init.js:63:209)
    at Object.<anonymous> (http://mylaptop:3344/webappbuilder/stemapp/jimu.js/dijit/Popup.js?wab_dv=2.2:443:20)
    at HTMLDivElement.<anonymous> (http://js.arcgis.com/3.18/init.js:63:209)
Uncaught TypeError: Cannot read property '_tables' of undefined(…)
Uncaught TypeError: Cannot read property '_tables' of undefined(…)
Uncaught TypeError: Cannot read property '_tables' of undefined(…)
Uncaught TypeError: Cannot read property '_tables' of undefined(…)
Uncaught TypeError: Cannot read property '_tables' of undefined(…)
Uncaught TypeError: Cannot read property '_tables' of undefined(…)
Object {layers: Object, review: false}
Uncaught TypeError: Cannot read property '_tables' of undefined(…)
Objectlayers: Objectreview: false__proto__: Object
Uncaught TypeError: Cannot read property '_tables' of undefined(…)

**Comment by sindile** [comment]
I had to enable the widget in Web AppBuilder
